-- =====================================================
-- GENERATE TEST CREW TASKS
-- Creates 20 different test tasks for shift management
-- =====================================================

-- Clear existing test tasks (optional - uncomment if needed)
-- DELETE FROM crew_tasks WHERE title LIKE '%Test%' OR title LIKE '%Airport%' OR title LIKE '%Training%';

-- Insert 20 diverse test tasks
INSERT INTO crew_tasks (
  id,
  task_number,
  task_type,
  task_status,
  driver_id,
  start_date,
  end_date,
  start_time,
  end_time,
  total_days,
  current_day,
  hours_per_day,
  total_hours,
  title,
  description,
  location,
  customer_name,
  customer_phone,
  priority,
  notes,
  is_multi_day,
  is_first_day,
  is_last_day,
  created_at,
  updated_at
) VALUES 
-- 1. Charter Services (5 tasks)
(
  gen_random_uuid(),
  1,
  'charter',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-07',
  '2025-10-07',
  '06:00:00',
  '10:00:00',
  1,
  1,
  4,
  4,
  'Early Morning Airport Transfer',
  'VIP client pickup from Haneda Airport to Tokyo Station',
  'Haneda Airport, Tokyo, Japan',
  'Mr. Tanaka',
  '+81-90-1234-5678',
  1,
  'High priority - VIP client',
  false,
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  2,
  'charter',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-08',
  '2025-10-08',
  '14:00:00',
  '18:00:00',
  1,
  1,
  4,
  4,
  'Business Executive Transfer',
  'Corporate transfer from Shibuya to Narita Airport',
  'Shibuya Station, Tokyo, Japan',
  'Ms. Suzuki',
  '+81-90-2345-6789',
  2,
  'Business class service required',
  false,
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  3,
  'charter',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-09',
  '2025-10-09',
  '08:00:00',
  '12:00:00',
  1,
  1,
  4,
  4,
  'Luxury Hotel Transfer',
  'Premium transfer from Imperial Hotel to Ginza',
  'Imperial Hotel, Tokyo, Japan',
  'Mr. Yamamoto',
  '+81-90-3456-7890',
  1,
  'Luxury vehicle required',
  false,
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  4,
  'charter',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-10',
  '2025-10-10',
  '16:00:00',
  '20:00:00',
  1,
  1,
  4,
  4,
  'Evening Airport Run',
  'Late evening transfer to Haneda Airport',
  'Roppongi, Tokyo, Japan',
  'Ms. Nakamura',
  '+81-90-4567-8901',
  2,
  'Evening rush hour traffic',
  false,
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  5,
  'charter',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-11',
  '2025-10-11',
  '10:00:00',
  '14:00:00',
  1,
  1,
  4,
  4,
  'Weekend City Tour',
  'Private city tour for international visitors',
  'Tokyo Station, Tokyo, Japan',
  'Mr. Smith',
  '+81-90-5678-9012',
  3,
  'English speaking driver preferred',
  false,
  true,
  true,
  NOW(),
  NOW()
),

-- 2. Regular Services (5 tasks)
(
  gen_random_uuid(),
  1,
  'regular',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-07',
  '2025-10-07',
  '09:00:00',
  '17:00:00',
  1,
  1,
  8,
  8,
  'Daily City Shuttle',
  'Regular shuttle service between major stations',
  'Shinjuku Station, Tokyo, Japan',
  'City Transport Co.',
  '+81-3-1234-5678',
  2,
  'Regular route service',
  false,
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  2,
  'regular',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-08',
  '2025-10-08',
  '07:00:00',
  '15:00:00',
  1,
  1,
  8,
  8,
  'Morning Commute Service',
  'Peak hour commuter service',
  'Ikebukuro Station, Tokyo, Japan',
  'Commute Solutions Ltd.',
  '+81-3-2345-6789',
  1,
  'High demand during rush hour',
  false,
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  3,
  'regular',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-09',
  '2025-10-09',
  '13:00:00',
  '21:00:00',
  1,
  1,
  8,
  8,
  'Afternoon Service Route',
  'Regular afternoon service route',
  'Shibuya Station, Tokyo, Japan',
  'Metro Transport',
  '+81-3-3456-7890',
  2,
  'Standard afternoon route',
  false,
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  4,
  'regular',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-10',
  '2025-10-10',
  '11:00:00',
  '19:00:00',
  1,
  1,
  8,
  8,
  'Midday Service',
  'Regular midday service operations',
  'Ueno Station, Tokyo, Japan',
  'Tokyo Transport Co.',
  '+81-3-4567-8901',
  2,
  'Midday service route',
  false,
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  5,
  'regular',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-11',
  '2025-10-11',
  '08:00:00',
  '16:00:00',
  1,
  1,
  8,
  8,
  'Weekend Service',
  'Weekend regular service',
  'Harajuku Station, Tokyo, Japan',
  'Weekend Transport',
  '+81-3-5678-9012',
  3,
  'Weekend service operations',
  false,
  true,
  true,
  NOW(),
  NOW()
),

-- 3. Training Tasks (3 tasks)
(
  gen_random_uuid(),
  1,
  'training',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-07',
  '2025-10-09',
  '10:00:00',
  '16:00:00',
  3,
  1,
  6,
  18,
  'Safety Training Course',
  '3-day mandatory safety and customer service training',
  'Training Center, Shinagawa, Tokyo',
  'Training Department',
  '+81-3-6789-0123',
  1,
  'Mandatory for all drivers',
  true,
  true,
  false,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  2,
  'training',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-10',
  '2025-10-10',
  '09:00:00',
  '17:00:00',
  1,
  1,
  8,
  8,
  'Defensive Driving Course',
  'Advanced defensive driving techniques',
  'Driving School, Yokohama',
  'Safety Training Inc.',
  '+81-45-1234-5678',
  2,
  'Advanced driving skills',
  false,
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  3,
  'training',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-11',
  '2025-10-11',
  '14:00:00',
  '18:00:00',
  1,
  1,
  4,
  4,
  'Customer Service Workshop',
  'Customer service excellence training',
  'Conference Room, Main Office',
  'HR Department',
  '+81-3-7890-1234',
  3,
  'Soft skills development',
  false,
  true,
  true,
  NOW(),
  NOW()
),

-- 4. Maintenance Tasks (3 tasks)
(
  gen_random_uuid(),
  1,
  'maintenance',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-07',
  '2025-10-07',
  '08:00:00',
  '12:00:00',
  1,
  1,
  4,
  4,
  'Vehicle Inspection',
  'Monthly vehicle safety inspection',
  'Service Center, Chiba',
  'Maintenance Team',
  '+81-43-1234-5678',
  1,
  'Critical safety inspection',
  false,
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  2,
  'maintenance',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-08',
  '2025-10-08',
  '10:00:00',
  '14:00:00',
  1,
  1,
  4,
  4,
  'Engine Service',
  'Regular engine maintenance and oil change',
  'Auto Service Center, Saitama',
  'Mechanical Team',
  '+81-48-1234-5678',
  2,
  'Regular maintenance schedule',
  false,
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  3,
  'maintenance',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-09',
  '2025-10-09',
  '13:00:00',
  '17:00:00',
  1,
  1,
  4,
  4,
  'Interior Cleaning',
  'Deep cleaning and sanitization',
  'Cleaning Facility, Tokyo',
  'Cleaning Team',
  '+81-3-8901-2345',
  3,
  'Hygiene and cleanliness',
  false,
  true,
  true,
  NOW(),
  NOW()
),

-- 5. Meeting Tasks (2 tasks)
(
  gen_random_uuid(),
  1,
  'meeting',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-07',
  '2025-10-07',
  '14:00:00',
  '16:00:00',
  1,
  1,
  2,
  2,
  'Team Briefing',
  'Weekly team meeting and updates',
  'Main Office, Shinjuku',
  'Management Team',
  '+81-3-9012-3456',
  2,
  'Weekly team coordination',
  false,
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  2,
  'meeting',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-10',
  '2025-10-10',
  '15:00:00',
  '17:00:00',
  1,
  1,
  2,
  2,
  'Safety Review Meeting',
  'Monthly safety review and planning',
  'Conference Room, Main Office',
  'Safety Committee',
  '+81-3-0123-4567',
  1,
  'Safety protocol review',
  false,
  true,
  true,
  NOW(),
  NOW()
),

-- 6. Day Off Tasks (2 tasks)
(
  gen_random_uuid(),
  1,
  'day_off',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-08',
  '2025-10-08',
  '00:00:00',
  '23:59:59',
  1,
  1,
  0,
  0,
  'Scheduled Day Off',
  'Planned day off for driver rest',
  'N/A',
  'N/A',
  'N/A',
  3,
  'Rest and recovery day',
  false,
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  2,
  'day_off',
  'scheduled',
  NULL, -- Unassigned
  '2025-10-11',
  '2025-10-11',
  '00:00:00',
  '23:59:59',
  1,
  1,
  0,
  0,
  'Weekend Day Off',
  'Weekend rest day',
  'N/A',
  'N/A',
  'N/A',
  3,
  'Weekend rest period',
  false,
  true,
  true,
  NOW(),
  NOW()
);

-- Update task numbers for multi-day tasks
UPDATE crew_tasks 
SET task_number = 2, current_day = 2, is_first_day = false, is_last_day = false
WHERE title = 'Safety Training Course' AND start_date = '2025-10-08';

UPDATE crew_tasks 
SET task_number = 3, current_day = 3, is_first_day = false, is_last_day = true
WHERE title = 'Safety Training Course' AND start_date = '2025-10-09';

-- Add some assigned tasks for demonstration
UPDATE crew_tasks 
SET driver_id = (SELECT id FROM drivers WHERE first_name = 'Takeshi' LIMIT 1)
WHERE title IN ('Early Morning Airport Transfer', 'Business Executive Transfer');

UPDATE crew_tasks 
SET driver_id = (SELECT id FROM drivers WHERE first_name = 'Yuki' LIMIT 1)
WHERE title IN ('Daily City Shuttle', 'Morning Commute Service');

UPDATE crew_tasks 
SET driver_id = (SELECT id FROM drivers WHERE first_name = 'Hiroshi' LIMIT 1)
WHERE title IN ('Safety Training Course', 'Vehicle Inspection');

-- Display summary
SELECT 
  task_type,
  COUNT(*) as task_count,
  COUNT(CASE WHEN driver_id IS NULL THEN 1 END) as unassigned_count,
  COUNT(CASE WHEN driver_id IS NOT NULL THEN 1 END) as assigned_count
FROM crew_tasks 
WHERE title IN (
  'Early Morning Airport Transfer', 'Business Executive Transfer', 'Luxury Hotel Transfer',
  'Evening Airport Run', 'Weekend City Tour', 'Daily City Shuttle', 'Morning Commute Service',
  'Afternoon Service Route', 'Midday Service', 'Weekend Service', 'Safety Training Course',
  'Defensive Driving Course', 'Customer Service Workshop', 'Vehicle Inspection',
  'Engine Service', 'Interior Cleaning', 'Team Briefing', 'Safety Review Meeting',
  'Scheduled Day Off', 'Weekend Day Off'
)
GROUP BY task_type
ORDER BY task_type;
