name: Security Scan

on:
  schedule:
    # Run daily at 3 AM UTC
    - cron: '0 3 * * *'
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate

      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --json-file-output=snyk-results.json

      - name: Upload Snyk results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: snyk-results.json

      - name: Comment PR with security scan results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            try {
              const snykResults = JSON.parse(fs.readFileSync('snyk-results.json', 'utf8'));
              const vulnerabilities = snykResults.vulnerabilities || [];
              
              if (vulnerabilities.length > 0) {
                const comment = `## 🔒 Security Scan Results
                
                Found ${vulnerabilities.length} security vulnerabilities:
                
                ${vulnerabilities.map(vuln => 
                  `- **${vuln.severity.toUpperCase()}**: ${vuln.title} (${vuln.packageName}@${vuln.version})`
                ).join('\n')}
                
                Please review and update dependencies as needed.`;
                
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: comment
                });
              } else {
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: '## 🔒 Security Scan Results\n\n✅ No security vulnerabilities found!'
                });
              }
            } catch (error) {
              console.log('No Snyk results to process');
            }
